server:
  #  address: 0.0.0.0
  port: 8080
#  servlet:
#    context-path: /api

spring:
  servlet:
    multipart:
      max-file-size: 20MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my healthcheck-in app
    username: root
    password: root
  #    username: user_my_healthcheck-in_app
  #    password: Mysql@8080
  profiles:
    active: dev
#  security:
#    user:
#      name: user
#      password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: edu.vojago.backend_healthcheckinsystem.handler

management:
  endpoint:
    env:
      show-values: always
