server:
  port: 8080
  servlet:
    context-path: /start
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my healthcheck-in app
    username: root
    password: root